### PR TITLE
Revert "🚀 Swtich to nvim-lsp"

### PR DESCRIPTION
**Pull request by voitd**
Reverts voitd/dotfiles#2

### CODE REVIEW

**Comment by felippepuhle** [comment]
@voitd any particular reason about reverting this? I'm currently using `coc` but I'm taking a look at `nvim-lsp` and it seems great, I already tested a bit but I wasn't able to make the autocompletion and ESlint to work properly... did it work for you? thanks!

**Comment by voitd** [comment]
Hey @felippepuhle!

Then I was just starting to move to nvim-lsp and I could not configure everything, there were difficulties with configuring the nvim-completions and the tsserver. Configuration in its current state works perfectly for me! I recommend the version from the last commit, it works very stable and very quickly and is definitely not as resource-intensive as with coc 😆 .

**Comment by felippepuhle** [comment]
Thanks @voitd! I'll take a look on it! Although I don't really understand how it works and it has a lot of configs (my current config is just some vimscript files for now), is there a reason why people are migrating all dotfiles to lua?

**Comment by voitd** [comment]
@felippepuhle

I don't know why everyone does it. My reason in the habit of programming "one module is one responsibility". Plus, it is more convenient to search for settings through a `fzf` or a `telescope`. But yes, sometimes I myself get lost in this location of files

**Pull request merged**
